In [1]:
#INSTALLING NumpPy....
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
#Import NumPy with Alias and Check Version....
import numpy as np
np.__version__, np.__path__

('1.21.5', ['C:\\Users\\ASCC\\anaconda3\\lib\\site-packages\\numpy'])

In [4]:
#CREATING NumPy Arrays....

np.sctypes #datatypes allowed in creating numpy arrays...

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64],
 'complex': [numpy.complex64, numpy.complex128],
 'others': [bool, object, bytes, str, numpy.void]}

In [5]:
#Creating an Empty Array...
arr=np.array([]) #empty seq is passed
print(arr)
print(type(arr))

[]
<class 'numpy.ndarray'>


In [6]:
#Creating a 0-D Array...
arr=np.array(10) #has a scalar value and no axis at all
print(arr) #only 1 element


10


In [9]:
#Creating 1-D Arrays....
arr=np.array([1,3,5,7,9], dtype=np.uint16) #2 bytes integer
print("Array :", arr)
print("Array.ndim :", arr.ndim)#tells the dimension i.e. 1D, 2D, 3D, etc.
print("Array.shape :", arr.shape) #returns a tuple(,) with (#of cols,) in 1D
print("Array.size :", arr.size) #total no of elements
print("Array.dtype :", arr.dtype) #data type of elements
print("Array.itemsize :", arr.itemsize) #size in bytes of each elements
print("Array.nbytes :", arr.nbytes) #total size in bytes of all elements..


Array : [1 3 5 7 9]
Array.ndim : 1
Array.shape : (5,)
Array.size : 5
Array.dtype : uint16
Array.itemsie : 2
Array.nbytes : 10


In [11]:
#CREATING 2D Arrays....
list1=[
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
arr2d=np.array(list1, dtype=np.uint16)
print("Array :", arr2d)
print("Array.ndim :", arr2d.ndim)#tells the dimension i.e. 1D, 2D, 3D, etc.
print("Array.shape :", arr2d.shape) #returns a tuple(,) with (rows,cols) in 2D
print("Array.size :", arr2d.size) #total no of elements
print("Array.dtype :", arr2d.dtype) #data type of elements
print("Array.itemsize :", arr2d.itemsize) #size in bytes of each elements
print("Array.nbytes :", arr2d.nbytes) #total size in bytes of all elements..


Array : [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Array.ndim : 2
Array.shape : (4, 4)
Array.size : 16
Array.dtype : uint16
Array.itemsize : 2
Array.nbytes : 32


In [14]:
#Creating 3-D Arrays...
list2=[
    [[1,2,3,4],[4,3,2,1]],
    [[5,6,7,8],[8,7,6,5]],
    [[9,10,11,12],[12,11,10,9]]
]
arr3d=np.array(list2, dtype=np.uint32)
print("Array :\n", arr3d)
print("Array.ndim :", arr3d.ndim)#tells the dimension i.e. 1D, 2D, 3D, etc.
print("Array.shape :", arr3d.shape) #returns a tuple(,) with (levels,rows, cols) in 3D 
print("Array.size :", arr3d.size) #total no of elements
print("Array.dtype :", arr3d.dtype) #data type of elements
print("Array.itemsize :", arr3d.itemsize) #size in bytes of each elements
print("Array.nbytes :", arr3d.nbytes) #total size in bytes of all elements..

Array :
 [[[ 1  2  3  4]
  [ 4  3  2  1]]

 [[ 5  6  7  8]
  [ 8  7  6  5]]

 [[ 9 10 11 12]
  [12 11 10  9]]]
Array.ndim : 3
Array.shape : (3, 2, 4)
Array.size : 24
Array.dtype : uint32
Array.itemsize : 4
Array.nbytes : 96


In [23]:
#Misellaneous Array Creation..
#1. np.zeros(shape, dtype=float)
marr=np.zeros(5)#default foat 
print("1D Zero's: \n",marr)
marr2=np.zeros((3,4))
print("2D Zero's: \n",marr2)
marr3=np.zeros((2,3), dtype=np.uint16)
print("2D Zero's with uint16: \n",marr3)

1D Zero's: 
 [0. 0. 0. 0. 0.]
2D Zero's: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2D Zero's with uint8: 
 [[0 0 0]
 [0 0 0]]


In [25]:
#2 np.ones(shape, dtype=float)
oarr=np.ones(3)#default foat 
print("1D Ones's: \n",oarr)
oarr2=np.ones((3,2))
print("2D Ones's: \n",oarr2)
oarr3=np.ones((2,3), dtype=np.uint32)
print("2D Ones's with uint16: \n",oarr3)

1D Ones's: 
 [1. 1. 1.]
2D Ones's: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
2D Ones's with uint16: 
 [[1 1 1]
 [1 1 1]]


In [30]:
 #3. numpy.empty(shape, dtype=float)
earr=np.empty(4) #array with junk values
print("Empty array \n", earr)
earr2=np.empty((2,4)) #array with junk values
print("Empty array \n", earr2)
earr3=np.empty((2,4), dtype=np.uint32) #array with junk values
print("Empty array \n", earr3)

Empty array 
 [5.56274831e-309 1.11255178e-308 1.66882874e-308 2.22510569e-308]
Empty array 
 [[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.32801506e-321 1.37959740e-306 2.29175545e-312]]
Empty array 
 [[ 131073  262147  393221  524295]
 [ 655369  786443  917517 1048591]]


In [33]:
#4. numpy.full(shape, fill_value, dtype-NONE)
farr=np.full(4, 33) #fill the array of given size with the given fill_value
print("Full arr :\n", farr)
farr2=np.full((2,4), 11) 
print("Full arr :\n", farr2)
farr3=np.full((3,4), 3, dtype=np.uint8)
print("Full arr :\n", farr3)

Full arr :
 [33 33 33 33]
Full arr :
 [[11 11 11 11]
 [11 11 11 11]]
Full arr :
 [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [37]:
#5. np.eye(N, M=None, k=0, dtype=float)  ->default conditions
darr=np.eye(4) #4*4 matrix wth main diagnol as "1"
print("Matrix with main diagnol \n", darr) #N=4, M=4, k=0, Dtype=float

darr2=np.eye(5,5,k=1, dtype=np.uint16)
print("Matrix with upper diagnol \n", darr2) #N=3, M=4, k=1, dtype=uint16

darr3=np.eye(4,5, k=-1, dtype=np.uint16)
print("Matrix with lower diagnol \n", darr3) #N=4, M=5, k=-1, dtype=uint16

Matrix with main diagnol 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Matrix with upper diagnol 
 [[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]
Matrix with lower diagnol 
 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]


In [49]:
#6. fromstring(string, sep=' ', dtype=float)
sarr=np.fromstring("3.4 5.7 7.8 2.1", sep=' ')#create an array from string gven and separate elements on sep basis in float type 
print("Array from string: \n", sarr)

sarr2=np.fromstring('3.45.77.82.1', sep='.', dtype=np.uint16)#elemenst separated at '.' of datatype=uint16
print("Array from string: \n", sarr2)


sarr3=np.fromstring('0.4,0.7,0.8,0.1', sep=',', dtype=np.uint16)#seaparate on comma basis and uint16 so all values is 0
print("Array from string: \n", sarr3)

Array from string: 
 [3.4 5.7 7.8 2.1]
Array from string: 
 [ 3 45 77 82  1]
Array from string: 
 [0]


C:\Users\ASCC\AppData\Local\Temp\ipykernel_7184\1967138912.py:9: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  sarr3=np.fromstring('0.4,0.7,0.8,0.1', sep=',', dtype=np.uint16)#seaparate on comma basis and uint16 so all values is 0


In [52]:
#7. np.arange(start(inclusive), stop(not inclusive), step) ->all args can be int or float
rarr=np.arange(6) #default data type in int64 of elements in range from 0 to 6(not inclusive)
print(rarr)

rarr1=np.arange(8, dtype=float)#data type is flaot of elements in range from 0 to 8(not inclusive)
print(rarr1)

rarr2=np.arange(4, 10)#range from 4 to 10(not inclusive) with step=1
print(rarr2)

rarr3=np.arange(5, 15, 3)#range from 5 to 15(not inclusive) with step=3
print(rarr3)


#FLOAT VALUE STEP
rarr4=np.arange(5, 15, 1.5)#range from 5 to 15(not inclusive) with step=1.5 float
print(rarr4)


#NEGATIVE STEP VALUE-> but for that start>stop mustly
rarr5=np.arange(10, 5, -2)#from 10 to 5(not inclusive) with step=-2 (-ve step)
print(rarr5)

rarr6=np.arange(10, 5, -1.5)#from 10 to 5(not inclusive) with step=-1.5 (float -ve step)
print(rarr6)

[0 1 2 3 4 5]
[0. 1. 2. 3. 4. 5. 6. 7.]
[4 5 6 7 8 9]
[ 5  8 11 14]
[ 5.   6.5  8.   9.5 11.  12.5 14. ]
[10  8  6]
[10.   8.5  7.   5.5]


In [58]:
#8.  linspace(start(incl), stop(incl), num=50)->return an arary of 50 equally spaced elements from strat->stop(both inclusive)

larr=np.linspace(1,3)#50 equally spaced elements from 1 to 3(incl)
print(larr)

larr2=np.linspace(3, 6, 3)#3 equally spaced elements from 3 to 6(incl)
print(larr2)

larr3=np.linspace(3, 6, 10)#10 equally spaced elements from 3 to 6(incl)
print(larr3)

#Negative start/stop values
larr3=np.linspace(-2, -8, 11)#11 equally spaced elements from -2 to 6-8(incl)
print(larr3)

[1.         1.04081633 1.08163265 1.12244898 1.16326531 1.20408163
 1.24489796 1.28571429 1.32653061 1.36734694 1.40816327 1.44897959
 1.48979592 1.53061224 1.57142857 1.6122449  1.65306122 1.69387755
 1.73469388 1.7755102  1.81632653 1.85714286 1.89795918 1.93877551
 1.97959184 2.02040816 2.06122449 2.10204082 2.14285714 2.18367347
 2.2244898  2.26530612 2.30612245 2.34693878 2.3877551  2.42857143
 2.46938776 2.51020408 2.55102041 2.59183673 2.63265306 2.67346939
 2.71428571 2.75510204 2.79591837 2.83673469 2.87755102 2.91836735
 2.95918367 3.        ]
[3.  4.5 6. ]
[3.         3.33333333 3.66666667 4.         4.33333333 4.66666667
 5.         5.33333333 5.66666667 6.        ]
[-2.  -2.6 -3.2 -3.8 -4.4 -5.  -5.6 -6.2 -6.8 -7.4 -8. ]


In [61]:
#9. random.rand() #array of floats from "0-1"
import random
print(np.random.rand()) #single scalar if no arg is passed from(0-1)
print(np.random.rand(5)) #array for #of value=arg passed from (0-1)
print(np.random.rand(4)*10) #array for #of value=arg passed from (0-10)
print(np.random.rand(2,3)*15) #2d array row=1ard cols=2arag from(0-15)
print(np.random.rand(2,4,3)) #3d array of levels=1st arg, rows=2nd arg, cols= 3rd arg from (0-1)


0.06041594319481902
[0.15759252 0.35373089 0.11573605 0.49296156 0.92357952]
[5.88256839 2.97813747 2.59216425 5.72082388]
[[ 9.23387546  7.10709519 13.97433619]
 [10.11595825 10.7229232   3.43611391]]
[[[0.97058937 0.635233   0.98587061]
  [0.75061017 0.30121169 0.50014482]
  [0.70889618 0.70921927 0.05742831]
  [0.28695942 0.97544653 0.06594978]]

 [[0.24641675 0.93062289 0.24435147]
  [0.38646127 0.67619908 0.55071204]
  [0.76572149 0.53497501 0.61451484]
  [0.75168272 0.69978217 0.99265375]]]


In [78]:
#10. random.randint(low , high=None, size) low>high
print(np.random.randint(2)) #random int from 0-2(2 exclusive)
print(np.random.randint(2, 6)) #random int from 2-6(6 exclusive)
print(np.random.randint(-3, 6)) #random int from 3 to 6(6 exclusive)
print(np.random.randint(2, 6, 5)) #1d-array of 5 elements having random ints from 2-6(6 exclusive) 
print(np.random.randint(2, 6, (2,2))) #2d-array of 2*2 elements having random ints from 2-6(6 exclusive)
print(np.random.randint(-2, 8, (2,3,2))) #2d-array of 2 levels of 3*2 elements having random ints from -2to 8(6 exclusive)

0
5
5
[4 5 4 5 3]
[[2 3]
 [3 4]]
[[[ 0  7]
  [ 5 -1]
  [ 7  7]]

 [[ 7 -1]
  [ 1  4]
  [ 0 -1]]]


In [80]:
#11. zeros-like(arr) 
l2= [[1,2,3], [4,5,6]]
l2arr=np.array(l2)
print(l2arr)

zarr=np.zeros_like(l2arr)
print(zarr)

[[1 2 3]
 [4 5 6]]
[[0 0 0]
 [0 0 0]]


In [82]:
a3=np.arange(10)
print(a3)
print(np.zeros_like(a3))

[0 1 2 3 4 5 6 7 8 9]
[0 0 0 0 0 0 0 0 0 0]
