In [2]:
import numpy as np
np.__version__

'1.21.5'

In [4]:
#OPERATIONS.....
arr=np.random.randint(5,100,10)

Original Array: [80 98 56 46 66  7 80 32 95 54]


In [12]:
#1. Scalar Math....
#1D Arrays
#Broadcasting in Array
print("Original Array:", arr)
print("Addition of 5:", arr+5) #add 5 in all elements of array
print("Subtraction 2 :", np.subtract(arr,2)) #subtract 5 in all elements of array
print("Division by 4:", arr/4)
print("Multiplication of 3:", np.multiply(arr,3))
print("Modulus of 3:", arr%3)

arr1=arr%3
print(id(arr), id(arr1)) #diff arrays

Original Array: [80 98 56 46 66  7 80 32 95 54]
Addition of 5: [ 85 103  61  51  71  12  85  37 100  59]
Subtraction 2 : [78 96 54 44 64  5 78 30 93 52]
Division by 4: [20.   24.5  14.   11.5  16.5   1.75 20.    8.   23.75 13.5 ]
Multiplication of 3: [240 294 168 138 198  21 240  96 285 162]
Modulus of 3: [2 2 2 1 0 1 2 2 2 0]
1750761648368 1750778393008


In [14]:
#2D Arrays
a2d=np.random.randint(0,50,(4,3))
print("Original 2D: \n", a2d)

Original 2D: 
 [[ 2 41 43]
 [ 9  2 45]
 [ 3 28 31]
 [38  2 21]]


In [21]:
print("Original Array:\n", a2d)
print("Addition of 3:\n", np.add(a2d,3)) #add 5 in all elements of array
print("Subtraction 3 :\n", np.subtract(a2d,3)) #subtract 5 in all elements of array
print("Multiplication by 2:\n", np.multiply(a2d,2))
print("Division of 3:\n", np.divide(a2d,3))
print("Modulus of 3:\n", np.mod(a2d,3))

Original Array:
 [[ 2 41 43]
 [ 9  2 45]
 [ 3 28 31]
 [38  2 21]]
Addition of 3:
 [[ 5 44 46]
 [12  5 48]
 [ 6 31 34]
 [41  5 24]]
Subtraction 3 :
 [[-1 38 40]
 [ 6 -1 42]
 [ 0 25 28]
 [35 -1 18]]
Multiplication by 2:
 [[ 4 82 86]
 [18  4 90]
 [ 6 56 62]
 [76  4 42]]
Division of 3:
 [[ 0.66666667 13.66666667 14.33333333]
 [ 3.          0.66666667 15.        ]
 [ 1.          9.33333333 10.33333333]
 [12.66666667  0.66666667  7.        ]]
Modulus of 3:
 [[2 2 1]
 [0 2 0]
 [0 1 1]
 [2 2 0]]


In [23]:
#3D Arrays
a3d=np.random.randint(0,50,(2,3,3))
print("Original 2D: \n", a3d)

Original 2D: 
 [[[21  2 29]
  [10 21 33]
  [10 42  1]]

 [[35 47 39]
  [43 22  1]
  [31  2 36]]]


In [24]:
print("Original Array:\n", a3d)
print("Addition of 3:\n", np.add(a3d,3)) #add 5 in all elements of array
print("Subtraction 3 :\n", np.subtract(a3d,3)) #subtract 5 in all elements of array
print("Multiplication by 2:\n", np.multiply(a3d,2))
print("Division of 3:\n", np.divide(a3d,3))
print("Modulus of 3:\n", np.mod(a3d,3))

Original Array:
 [[[21  2 29]
  [10 21 33]
  [10 42  1]]

 [[35 47 39]
  [43 22  1]
  [31  2 36]]]
Addition of 3:
 [[[24  5 32]
  [13 24 36]
  [13 45  4]]

 [[38 50 42]
  [46 25  4]
  [34  5 39]]]
Subtraction 3 :
 [[[18 -1 26]
  [ 7 18 30]
  [ 7 39 -2]]

 [[32 44 36]
  [40 19 -2]
  [28 -1 33]]]
Multiplication by 2:
 [[[42  4 58]
  [20 42 66]
  [20 84  2]]

 [[70 94 78]
  [86 44  2]
  [62  4 72]]]
Division of 3:
 [[[ 7.          0.66666667  9.66666667]
  [ 3.33333333  7.         11.        ]
  [ 3.33333333 14.          0.33333333]]

 [[11.66666667 15.66666667 13.        ]
  [14.33333333  7.33333333  0.33333333]
  [10.33333333  0.66666667 12.        ]]]
Modulus of 3:
 [[[0 2 2]
  [1 0 0]
  [1 0 1]]

 [[2 2 0]
  [1 1 1]
  [1 2 0]]]


In [32]:
#Experiment.....
aa2=np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=np.int16, order='C')
print(aa2)
print(aa2-3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]


In [34]:
#2.ARITHEMATIC OPERATIONS...
#1D Arrays...
opa=np.random.randint(1,10,4)
opa1=np.random.randint(1,10,4)
print("Array 1:",opa)
print("Array 2:",opa1)

Array 1: [7 2 6 3]
Array 2: [3 2 8 1]


In [35]:
print("Addition:", np.add(opa,opa1)) #add 5 in all elements of array
print("Subtraction:", np.subtract(opa,opa1)) #subtract 5 in all elements of array
print("Multiplication:", np.multiply(opa,opa1))
print("Division:", np.divide(opa,opa1))
print("Modulus:", np.mod(opa,opa1))

Addition: [10  4 14  4]
Subtraction: [ 4  0 -2  2]
Multiplication: [21  4 48  3]
Division: [2.33333333 1.         0.75       3.        ]
Modulus: [1 0 6 0]


In [37]:
#2D Arrays...
mat1=np.random.randint(1,10,(2,2))
mat2=np.random.randint(1,10,(2,2))
print("Array 1:\n",mat1)
print("Array 2:\n",mat2)

Array 1:
 [[8 1]
 [2 4]]
Array 2:
 [[6 6]
 [7 3]]


In [39]:
print("Addition:\n", np.add(mat1,mat2)) #add 5 in all elements of array
print("Subtraction:\n", np.subtract(mat1,mat2)) #subtract 5 in all elements of array
print("Multiplication:\n", np.multiply(mat1,mat2))
print("Division:\n", np.divide(mat1,mat2))
print("Modulus:\n", np.mod(mat1,mat2))

Addition:
 [[14  7]
 [ 9  7]]
Subtraction:
 [[ 2 -5]
 [-5  1]]
Multiplication:
 [[48  6]
 [14 12]]
Division:
 [[1.33333333 0.16666667]
 [0.28571429 1.33333333]]
Modulus:
 [[2 1]
 [2 1]]


In [40]:
#23 Arrays...
matrix1=np.random.randint(1,10,(2,3,3))
matrix2=np.random.randint(1,10,(2,3,3))
print("Matrix 1:\n",matrix1)
print("Matrix 2:\n",matrix2)

Matrix 1:
 [[[7 1 7]
  [6 9 9]
  [2 1 6]]

 [[4 9 4]
  [7 6 7]
  [9 4 2]]]
Matrix 2:
 [[[2 6 5]
  [7 5 7]
  [1 4 6]]

 [[8 6 8]
  [3 4 4]
  [5 2 7]]]


In [41]:
print("Addition:\n", np.add(matrix1,matrix2)) #add 5 in all elements of array
print("Subtraction:\n", np.subtract(matrix1,matrix2)) #subtract 5 in all elements of array
print("Multiplication:\n", np.multiply(matrix1,matrix2))
print("Division:\n", np.divide(matrix1,matrix2))
print("Modulus:\n", np.mod(matrix1,matrix2))

Addition:
 [[[ 9  7 12]
  [13 14 16]
  [ 3  5 12]]

 [[12 15 12]
  [10 10 11]
  [14  6  9]]]
Subtraction:
 [[[ 5 -5  2]
  [-1  4  2]
  [ 1 -3  0]]

 [[-4  3 -4]
  [ 4  2  3]
  [ 4  2 -5]]]
Multiplication:
 [[[14  6 35]
  [42 45 63]
  [ 2  4 36]]

 [[32 54 32]
  [21 24 28]
  [45  8 14]]]
Division:
 [[[3.5        0.16666667 1.4       ]
  [0.85714286 1.8        1.28571429]
  [2.         0.25       1.        ]]

 [[0.5        1.5        0.5       ]
  [2.33333333 1.5        1.75      ]
  [1.8        2.         0.28571429]]]
Modulus:
 [[[1 1 2]
  [6 4 2]
  [0 1 0]]

 [[4 3 4]
  [1 2 3]
  [4 0 2]]]


In [44]:
#3. MORE Arithematic Operations...

#1D ARRAY
marr=np.random.rand(5)*10
print(marr)

[8.13296556 7.65431659 8.68041043 2.29711374 1.45556134]


In [46]:
print("absolute",np.abs(marr))
print("square",np.square(marr))
print("square root",np.sqrt(marr))
print("cube root",np.cbrt(marr))
print("log with base e",np.log(marr))
print("log with base 2",np.log2(marr))
print("log with base 10",np.log10(marr))
print("Return True if an element is not a number",np.isnan(marr))
print("Ceil of value: ",np.ceil(marr))
print("Floor: ",np.floor(marr))
print("Cummulative sum along the axix",np.cumsum(marr))

absolute [8.13296556 7.65431659 8.68041043 2.29711374 1.45556134]
square [66.14512879 58.58856243 75.34952528  5.27673156  2.11865883]
square root [2.85183547 2.76664356 2.94625363 1.51562322 1.20646647]
cube root [2.01101964 1.97076787 2.05516528 1.31945373 1.13329639]
log with base e [2.09592562 2.03526975 2.16106881 0.83165344 0.37539163]
log with base 2 [3.0237815  2.93627357 3.11776326 1.1998223  0.54157564]
log with base 10 [0.91024893 0.88390642 0.93854026 0.3611825  0.16303051]
Return True if an element is not a number [False False False False False]
Ceil of value:  [9. 8. 9. 3. 2.]
Floor:  [8. 7. 8. 2. 1.]
Cummulative sum along the axix [ 8.13296556 15.78728215 24.46769258 26.76480632 28.22036767]


In [47]:
#2D ARRAY...
marr2=np.random.randint(5,50,(3,3))
print(marr2)

[[19 18 48]
 [42 28 19]
 [32 39  9]]


In [49]:
print("square root\n",np.sqrt(marr2))
print("cube root\n",np.cbrt(marr2))
print("log with base e\n",np.log(marr2))
print("log with base 2\n",np.log2(marr2))
print("log with base 10\n",np.log10(marr2))

square root
 [[4.35889894 4.24264069 6.92820323]
 [6.4807407  5.29150262 4.35889894]
 [5.65685425 6.244998   3.        ]]
cube root
 [[2.66840165 2.62074139 3.63424119]
 [3.47602664 3.03658897 2.66840165]
 [3.1748021  3.39121144 2.08008382]]
log with base e
 [[2.94443898 2.89037176 3.87120101]
 [3.73766962 3.33220451 2.94443898]
 [3.4657359  3.66356165 2.19722458]]
log with base 2
 [[4.24792751 4.169925   5.5849625 ]
 [5.39231742 4.80735492 4.24792751]
 [5.         5.28540222 3.169925  ]]
log with base 10
 [[1.2787536  1.25527251 1.68124124]
 [1.62324929 1.44715803 1.2787536 ]
 [1.50514998 1.59106461 0.95424251]]


In [59]:
#4. Aggregate Functions... (returns aggerated single value after applying the function)
#1D Arrays....
print(opa)
print("Maximum:", np.max(opa))
print("Minimum:", np.min(opa))
print("sum:", np.sum(opa)) #sum of all values
print("product:", np.prod(opa)) #product of all values
print("Mean:", np.mean(opa)) #summ al values divide by no of elements
print("Average:", np.average(opa)) #works with weighted average/mean

wts=[3,4,2,1]
print("Average with weights:", np.average(opa, weights=wts))#((7*3+2*4+2*6+3*1)/7+2+6+3)
print("Median:", np.median(opa))
print("Percentile at 0:", np.percentile(opa,0))
print("Percentile at 50:", np.percentile(opa,50))
print("Percentile at 100:", np.percentile(opa,100))
print("Variance:", np.var(opa))
print("Standard Deviation:", np.std(opa))

[7 2 6 3]
Maximum: 7
Minimum: 2
sum: 18
product: 252
Mean: 4.5
Average: 4.5
Average with weights: 4.4
Median: 4.5
Percentile at 0: 2.0
Percentile at 50: 4.5
Percentile at 100: 7.0
Variance: 4.25
Standard Deviation: 2.0615528128088303


In [64]:
#2D Arrays....
#for 2d aggregate functions axis is compulsory..
agarr=np.random.randint(1,100,(3,3))
print("Sum on 2d arrays axis 0:", np.sum(agarr,axis=0))
print("Sum on 2d arrays axis 1:", np.sum(agarr,axis=1))

Sum on 2d arrays axis 0: [165 199  97]
Sum on 2d arrays axis 1: [ 57 219 185]


In [67]:
print("Medain on 2d arrays axis 0:", np.median(agarr,axis=0))
print("Median on 2d arrays axis 1:", np.median(agarr,axis=1))

print("Mean on 2d arrays axis 0:", np.mean(agarr,axis=0))
print("Mean on 2d arrays axis 1:", np.mean(agarr,axis=1))

Medain on 2d arrays axis 0: [70. 79. 36.]
Median on 2d arrays axis 1: [23. 72. 70.]
Mean on 2d arrays axis 0: [55.         66.33333333 32.33333333]
Mean on 2d arrays axis 1: [19.         73.         61.66666667]


In [68]:
#3D Arrays....
#for 2d aggregate functions axis is compulsory..
agg3d=np.random.randint(1,100,(2,2,2,))
print(agg3d)

[[[33 52]
  [ 7 24]]

 [[29 23]
  [30  5]]]


In [81]:
print("sum on 3d arrays axis 0:\n", np.sum(agg3d,axis=0)) #fusion in sandwich form
print("sum on 3d arrays axis 1:\n", np.sum(agg3d,axis=1)) #layer by layer each coloum is added
print("sum on 3d arrays axis 2:\n", np.sum(agg3d,axis=2)) #layer by layer each row is added 

sum on 3d arrays axis 0:
 [[62 75]
 [37 29]]
sum on 3d arrays axis 1:
 [[40 76]
 [59 28]]
sum on 3d arrays axis 2:
 [[85 31]
 [52 35]]


In [85]:
#COMPARISON OPERATIONS...
#1D Arrays....
print(opa)
print(opa1)
print("Equal : ", opa == opa1)
print("Not Equal : ", opa != opa1)
print("Greater Equal : ", opa >= opa1)
print("Lesser Equal : ", opa <= opa1)

print("Greater : ", opa > opa1)
print("Lesser : ", opa < opa1)

[7 2 6 3]
[3 2 8 1]
Equal :  [False  True False False]
Not Equal :  [ True False  True  True]
Greater Equal :  [ True  True False  True]
Lesser Equal :  [False  True  True False]
Greater :  [ True False False  True]
Lesser :  [False False  True False]


In [88]:
#2d Arrays...
print(mat1)
print(mat2)
print("Equal :\n ", np.equal(mat1, mat2))
print("Not Equal :\n ", np.not_equal(mat1, mat2))
print("Greater Equal :\n ",np.greater_equal(mat1, mat2) )
print("Lesser Equal : \n", np.less_equal(mat1, mat2))

print("Greater : \n",np.greater(mat1, mat2) )
print("Lesser : \n",np.less(mat1, mat2) )

[[8 1]
 [2 4]]
[[6 6]
 [7 3]]
Equal :
  [[False False]
 [False False]]
Not Equal :
  [[ True  True]
 [ True  True]]
Greater Equal :
  [[ True False]
 [False  True]]
Lesser Equal : 
 [[False  True]
 [ True False]]
Greater : 
 [[ True False]
 [False  True]]
Lesser : 
 [[False  True]
 [ True False]]


In [96]:
#SEARCHING IN NUMPY ARRAYS...
#1D Arrays...

sarr= np.array([1,4,2,6,5,7,8,2,8,3])
s1=np.where(sarr >= 4) #return a tuple with (an array with all indexex where value is >= 4, dtype)
print("Array element searching", s1)


s2=np.where(sarr%2 == 0) #return a tuple with (an array with all indexex where value is >= 4, dtype)
print("Array element searching of evens", s2)

s3=np.where(sarr%2 == 0, True, False) #return an Array with True for which condition is true and false for false condition.
print("Array element searching of evens", s3)

Array element searching (array([1, 3, 4, 5, 6, 8], dtype=int64),)
Array element searching of evens (array([1, 2, 3, 6, 7, 8], dtype=int64),)
Array element searching of evens [False  True  True  True False False  True  True  True False]


In [100]:
#2D Arrays...
matrix= np.array([[4,2,6],[5,7,8],[2,8,3]])
s4=np.where(matrix==2) #return two tuples 1st->(rows with condition true) 2nd->(cols with true condition)
print("Array element searching", s4)

Array element searching (array([0, 2], dtype=int64), array([1, 0], dtype=int64))


In [103]:
#2D Arrays...
matrix3= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
s5=np.where(matrix3==2)
#return 3 tuples 1st->(layer with true condition) 2nd->(rows with condition true) 3rd->(cols with true condition)
print("Array element searching", s5)

s6=np.where(matrix3%2 ==0, True, False)
#return 3 tuples 1st->(layer with true condition) 2nd->(rows with condition true) 3rd->(cols with true condition)
print("Array element searching\n", s6)

Array element searching (array([0], dtype=int64), array([0], dtype=int64), array([1], dtype=int64))
Array element searching
 [[[False  True]
  [False  True]]

 [[False  True]
  [False  True]]]
