In [1]:
import numpy as np
np.__version__

'1.21.5'

In [4]:
#INDEXING OF NUMPY ARRAYS...

#1. 1D Arrays...
l1=[1,2,3,4,5,6,7,8,9,0]
arr=np.array(l1, dtype=np.uint8)
print("Orignal Array: ", arr, "Array Shape:", arr.shape)

#check indexing...
print(arr[0])
print(arr[-4])
print(arr[4])
print(arr[8])

#Error of index out of bound...
print(arr[11])
print(arr[-11])

Orinal Array:  [1 2 3 4 5 6 7 8 9 0] Array Shape: (10,)
1
7
5
9


IndexError: index 11 is out of bounds for axis 0 with size 10

In [10]:
#2. 2D Arrays...
l2=[
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [0,2,4]]
arr2=np.array(l2, dtype=np.uint8)
print("Orinal Array: \n", arr2, "\nArray Shape:", arr2.shape)

#check indexing...
print(arr2[2]) #entire row with only one index (3rd row in this case)
print(arr2[1][2]) #specific element of specific row (2nd row, 3rd col)
print(arr2[-1][-1]) #specific element of specific row (last row, last col)
print(arr2[-3]) #entire row with only one index (2nd last row in this case)

Orinal Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 2 4]] 
Array Shape: (4, 3)
[7 8 9]
6
4
[4 5 6]


In [100]:
#3. 3D Arrays...
l3=[
    [[1,2],[4,5],[7,8]],
    [[3,6],[0,9],[10,11]]
   ]
arr3=np.array(l3, dtype=np.uint8)
print("Orinal Array: \n", arr3, "\nArray Shape:", arr3.shape)

#for each level/layer we pass only one index
print("Level 1: \n",arr3[0])
print("Level 2: \n", arr3[1])

#for accessing specific row in specific layer...
print("Level 1->row(3): \n",arr3[0][2])
print("Level 2->row(1): \n", arr3[1][0])

#for accessing specific elements in specific layer and row...
print("Level 1->row(2)->col(2):",arr3[0][1][1])
print("Level 2->row(3)->col(1):", arr3[1][2][0])

#Nedative Indexing...
print("Level 1:\n",arr3[-2])
print("Level 2->row(2):", arr3[-1][-2])
print("Level 1->row(3)->col(2):",arr3[-2][-3][-1])

#mixed indexing
print("Level 1->row(3):", arr3[-2][2])

Orinal Array: 
 [[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[ 3  6]
  [ 0  9]
  [10 11]]] 
Array Shape: (2, 3, 2)
Level 1: 
 [[1 2]
 [4 5]
 [7 8]]
Level 2: 
 [[ 3  6]
 [ 0  9]
 [10 11]]
Level 1->row(3): 
 [7 8]
Level 2->row(1): 
 [3 6]
Level 1->row(2)->col(2): 5
Level 2->row(3)->col(1): 10
Level 1:
 [[1 2]
 [4 5]
 [7 8]]
Level 2->row(2): [0 9]
Level 1->row(3)->col(2): 2
Level 1->row(3): [7 8]


In [103]:
#INDEXING CAN BE COMMA SEPARATED AS WELL...
print(arr3[-2,2])
print(arr3[-1,1,-2])
print(arr3[-2,-3,-1])

[7 8]
0
2


In [32]:
#SLICING IN NUMPY ARRAYS....
#1. 1D Arrays...
print("Orignal Array: ", arr, "Array Shape:", arr.shape)

#SLICING...
print("\narr[:]->", arr[:]) #full array
print("arr[4:]->", arr[4:]) #from 4 to end
print("arr[:5]->", arr[:5]) #from 0 to 4
print("arr[2:8]->", arr[2:8]) #from 2 to 7
print("arr[3:9:2]->", arr[3:9:2]) #from 3 to 9 every 2nd element only

#slicing with negative values..
print("\narr[:-2]->", arr[:-2]) #from 0 to -2(2nd last)
print("arr[-1:]->", arr[-1:]) #from -1 to end (only one element cause default +ve index and last +ve index is -1 as well)
print("arr[-2:-7]->", arr[-2:-7]) #from -2 to -7 (empty cause deafult step is +1 here and start value must be greater than stop)
print("arr[-2:-7:-1]->", arr[-2:-7:-1]) #from -2 to -7 with -ve step of 1 in reverse order
print("arr[::-1]->", arr[::-1]) #whole array from right to left (reverse array)

Orignal Array:  [1 2 3 4 5 6 7 8 9 0] Array Shape: (10,)

arr[:]-> [1 2 3 4 5 6 7 8 9 0]
arr[4:]-> [5 6 7 8 9 0]
arr[:5]-> [1 2 3 4 5]
arr[2:8]-> [3 4 5 6 7 8]
arr[3:9:2]-> [4 6 8]

arr[:-2]-> [1 2 3 4 5 6 7 8]
arr[-1:]-> [0]
arr[-2:-7]-> []
arr[-2:-7:-1]-> [9 8 7 6 5]
arr[::-1]-> [0 9 8 7 6 5 4 3 2 1]


In [41]:
#Experiments...
print("Original Array: ", arr)
print("\narr[:-2:-2]->", arr[:-2:-2])#step -ve so unmentioned start/stop will be -ve so read from (-1 to -1 with -2 step)
print("arr[:-3:-2]->", arr[:-3:-2]) #(-1 to -2 with -2 step)
print("arr[:-4:-2]->", arr[:-4:-2]) #(-1 to -2 with -2 step)
print("arr[-2::-2]->", arr[-2::-2]) #(-2 to -len(array) with -2 step) stop is -len(array)
print("arr[-4::-3]->", arr[-4::-3]) #(-4 to -len(array) with -3 step) stop is -len(array)

print("Original Array same after all: ", arr)

Original Array:  [1 2 3 4 5 6 7 8 9 0]

arr[:-2:-2]-> [0]
arr[:-3:-2]-> [0]
arr[:-4:-2]-> [0 8]
arr[-2::-2]-> [9 7 5 3 1]
arr[-4::-3]-> [7 4 1]
Original Array same after all:  [1 2 3 4 5 6 7 8 9 0]


In [45]:
#PROOF OF CONCEPT

#Arrays slicing gives a view Vs List slicing gives a new array...
l2= l1[3:7]
print("Original List: ",l1)
print("New List from slicing",l2)
l2[2] = 99
print("Original List: ",l1)
print("New List from slicing",l2) # change only in new that means l1 and l2 are diff

Original List:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
New List from slicing [4, 5, 6, 7]
Original List:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
New List from slicing [4, 5, 99, 7]


In [49]:
# Now with Numpy Arrays
ar2= arr[2:8]
print("Original Array: ",arr)
print("New Array from slicing", ar2)
ar2[3] = 88 #value 6 is replaced with 88 in both places
print("\nOriginal Array: ",arr) #
print("New Array from slicing",ar2)

Original Array:  [ 1  2  3  4 22  6  7  8  9  0]
New Array from slicing [ 3  4 22  6  7  8]

Original Array:  [ 1  2  3  4 22 88  7  8  9  0]
New Array from slicing [ 3  4 22 88  7  8]


In [60]:
#2. 2D Array Slicing......
print("Original Array: \n", arr2)

#Slicing...
#2 objects of slicing are passes rather than 1 in this case (1st-> row range, 2nd-> col range)

# +ev ROW Variations....
print("\narr2[:,:]\n", arr2[:,:])  # here all row and all cols are selected for view
print("\narr2[1]\n", arr2[1])  # you can ignore col object if all cols are to be selected
print("\narr2[1, :]\n", arr2[1,:])  # here 2nd row and all cols are selected for view
print("\narr2[:2,:]\n", arr2[:2,:]) #from 1st to 2nd rows , all cols
print("\narr2[1:3,:]\n", arr2[1:3,:]) # from 2nd ro 3rd row, all cols

Original Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 2 4]]

arr2[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 2 4]]

arr2[1]
 [4 5 6]

arr2[1, :]
 [4 5 6]

arr2[:2,:]
 [[1 2 3]
 [4 5 6]]

arr2[1:3,:]
 [[4 5 6]
 [7 8 9]]


In [64]:
#+ve COL Variations...
print("Original Array: \n", arr2)
print("\narr2[:,:1]\n", arr2[:,:2]) #all rows , 1st to 2nd col
print("\narr2[:,2:]\n", arr2[:,2:]) #all rows, from 3rd to last col
print("\narr2[:,1:2]\n", arr2[:,1:2]) #all rows, from 2nd to 3rd col

Original Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 2 4]]

arr2[:,:1]
 [[1 2]
 [4 5]
 [7 8]
 [0 2]]

arr2[:,2:]
 [[3]
 [6]
 [9]
 [4]]

arr2[:,1:2]
 [[2]
 [5]
 [8]
 [2]]


In [65]:
 #can't ignore the row obj
print("\narr2[,1:2]\n", arr2[,1:2]) #Syntax error

SyntaxError: invalid syntax (1048572911.py, line 2)

In [66]:
# +ve R0W AND COL Variations...
print("Original Array: \n", arr2)
print("\narr2[1:,1:3]\n", arr2[1:,1:3]) 
print("\narr2[:2,1:2]\n", arr2[:2,1:2])

Original Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 2 4]]

arr2[1:,1:3]
 [[5 6]
 [8 9]
 [2 4]]

arr2[:2,1:2]
 [[2]
 [5]]


In [68]:
# -VE Slicing
print("Original Array: \n", arr2)
print("\narr2[1:,1:3]\n", arr2[:,::-1])  #revere cols in each row
print("\narr2[:2,1:2]\n", arr2[::-1,::-1]) # reverse all rows then cols in those rows
print("\narr2[:2,1:2]\n", arr2[::-1,:])  # reverse all rows and cols same

Original Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 2 4]]

arr2[1:,1:3]
 [[3 2 1]
 [6 5 4]
 [9 8 7]
 [4 2 0]]

arr2[:2,1:2]
 [[4 2 0]
 [9 8 7]
 [6 5 4]
 [3 2 1]]

arr2[:2,1:2]
 [[0 2 4]
 [7 8 9]
 [4 5 6]
 [1 2 3]]


In [72]:
print("Original Array: \n", arr2)
print("\narr2[1:,1:3]\n", arr2[-2:-4:-1,-2:-3:-1]) 
print("\narr2[1:,1:3]\n", arr2[-1::-2,-2:-3:-1]) 

Original Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 2 4]]

arr2[1:,1:3]
 [[8]
 [5]]

arr2[1:,1:3]
 [[2]
 [5]]


In [76]:
#3. 3D Slicing....
l4=[
    [[0,1,2],[3,4,5],[6,7,8]],
    [[11,22,33],[44,55,66],[77,88,99]],
    [[9,8,7],[6,5,4],[3,2,1]]
]
arr4 = np.array(l4,dtype=np.uint16)
print("Orinal Array: \n", arr4, "\nArray Shape", arr4.shape)

Orinal Array: 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]

 [[ 9  8  7]
  [ 6  5  4]
  [ 3  2  1]]] 
Array Shape (3, 3, 3)


In [81]:
#POSITIVE Slicing....
print("arr4[:,:,:]\n",arr4[:,:,:]) #all array
print("\narr4[:]\n",arr4[:]) # whole array you can ignore row and col obj if you want all row and col in any level

arr4[:,:,:]
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]

 [[ 9  8  7]
  [ 6  5  4]
  [ 3  2  1]]]

arr4[:]
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]

 [[ 9  8  7]
  [ 6  5  4]
  [ 3  2  1]]]


In [89]:
print("\narr4[2]:\n",arr4[2]) #only 3rd level (all rows and cols)
print("\narr4[1]:\n",arr4[1]) #only 2nd level (all rows and cols)
print("\narr4[-1]:\n",arr4[-1]) #only 3rd level (all rows and cols)
print("\narr4[-3]:\n",arr4[-3]) #only 2nd level (all rows and cols)


arr4[2]:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

arr4[1]:
 [[11 22 33]
 [44 55 66]
 [77 88 99]]

arr4[-1]:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

arr4[-3]:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [91]:
#Levels and Rows....
print("Orinal Array: \n", arr4)
print("\narr4[1:,1:]: \n",arr4[1:,1:]) #level 1 and 2 row 1 and 2 (all cols)
print("\narr4[0:2,-1:-3:-1]: \n",arr4[0:2,-1:-3:-1]) #level 1 and 2 row 1 and 2 (all cols)
print("\narr4[-1:,-1::-2]: \n",arr4[-1:,-1::-2]) #last level from bottom only as step +ve and all row from bottom with -2 step
print("\narr4[-1::-1,-1::-2]: \n",arr4[-1::-1,-1::-2]) #all level from bottom and all row from bottom with -2 step

Orinal Array: 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]

 [[ 9  8  7]
  [ 6  5  4]
  [ 3  2  1]]]

arr4[1:,1:]: 
 [[[44 55 66]
  [77 88 99]]

 [[ 6  5  4]
  [ 3  2  1]]]

arr4[0:2,-1:-3:-1]: 
 [[[ 6  7  8]
  [ 3  4  5]]

 [[77 88 99]
  [44 55 66]]]

arr4[-1:,-1::-2]: 
 [[[3 2 1]
  [9 8 7]]]

arr4[-1::-1,-1::-2]: 
 [[[ 3  2  1]
  [ 9  8  7]]

 [[77 88 99]
  [11 22 33]]

 [[ 6  7  8]
  [ 0  1  2]]]


In [96]:
#Levels and Rows and cols....
print("Orinal Array: \n", arr4)
print("\narr4[::-1]: \n",arr4[::-1])
print("\narr4[::-1,::-1]: \n",arr4[::-1,::-1])
print("\narr4[::-1,::-1,::-1]: \n",arr4[::-1,::-1,::-1])

Orinal Array: 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]

 [[ 9  8  7]
  [ 6  5  4]
  [ 3  2  1]]]

arr4[::-1]: 
 [[[ 9  8  7]
  [ 6  5  4]
  [ 3  2  1]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]]

arr4[::-1,::-1]: 
 [[[ 3  2  1]
  [ 6  5  4]
  [ 9  8  7]]

 [[77 88 99]
  [44 55 66]
  [11 22 33]]

 [[ 6  7  8]
  [ 3  4  5]
  [ 0  1  2]]]

arr4[::-1,::-1,::-1]: 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[99 88 77]
  [66 55 44]
  [33 22 11]]

 [[ 8  7  6]
  [ 5  4  3]
  [ 2  1  0]]]


In [97]:
#NEGATIVE SLICING IN 3D ARRAYS....

print("Orinal Array: \n", arr4)
print("\narr4[-1::-2, -2::-1, -1::-2]: \n",arr4[-1::-2,-2::-1,-1::-2])

Orinal Array: 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]

 [[ 9  8  7]
  [ 6  5  4]
  [ 3  2  1]]]

arr4[-1::-2, -2::-1, -1::-2]: 
 [[[4 6]
  [7 9]]

 [[5 3]
  [2 0]]]


In [111]:
#FANCY/BOOLEAN INDEXING...
#1. 1D fancy indexing...

farr=np.random.randint(2,88,10)
print("original:",farr)

#even values only
print("Evens in arrays: ", farr[farr%2==0])  #passing a condition in the subscript
 
#odd values only
print("Odd in arrays: ", farr[farr%2!=0])

#odd values only
print("Odds in arrays: ", farr[farr%2==1])

#values greater than 50 only
print("Values greater than equal 10 in arrays: ", farr[farr >= 50])

#join two conditions
print("Greater tahn 30 less than 90: ", farr[(farr>30) & (farr<90)])

original: [10 61 61  2 19  3 87 12 35 58]
Evens in arrays:  [10  2 12 58]
Odd in arrays:  [61 61 19  3 87 35]
Odds in arrays:  [61 61 19  3 87 35]
Values greater than equal 10 in arrays:  [61 61 87 58]
Greater tahn 30 less than 90:  [61 61 87 35 58]


In [121]:
print("original:",farr)
print("values divisible by 7 and 5 only ", farr[(farr%7==0) & (farr%5==0)])

values divisible by 7 and 5 only  [35]


In [123]:
#MASKING/BOOLEAN INDEXING..
print("original:",farr)
print("values greater than 40", farr>40) #returns boolean list by applying condition on every element of array
mask=[False, True, False, False, True, True,False, False, True, True]
print("\nmask array", farr[mask]) #only true values will be returned

original: [10 61 61  2 19  3 87 12 35 58]
values greater than 40 [False  True  True False False False  True False False  True]

mask array [61 19  3 35 58]


In [124]:
#2. 2D Fanccy Indexing.....
f2arr=np.random.randint(5,55,(4,3))
print("original 2D:\n", f2arr)

original 2D:
 [[15 36 23]
 [ 9 35 13]
 [14 47 42]
 [ 9 41 27]]


In [126]:
#row mask
row_mask=[True, False, True, True]
print("Row Mask:\n", f2arr[row_mask,:]) #all cols and masked rows

col_mask=[True, False, False]
print("Col Mask:\n", f2arr[:,col_mask]) #all rows and masked cols

Row Mask:
 [[15 36 23]
 [14 47 42]
 [ 9 41 27]]
Col Mask:
 [[15]
 [ 9]
 [14]
 [ 9]]


In [136]:
inner_row=np.array([False, True, True, True])
inner_col=np.array([False, True, True])
fil_matrix=np.array(f2arr[inner_row,:])
print("Right Lower Matrix: \n",fil_matrix[:,inner_col])


#BETTER WAY TO DO THIS IS 
print("with normal indexing\n",f2arr[1:,1:])


Right Lower Matrix: 
 [[35 13]
 [47 42]
 [41 27]]
with normal indexing
 [[35 13]
 [47 42]
 [41 27]]


IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [137]:
print("original 2D:\n", f2arr)
print("2D fancy: \n",f2arr[[True, True, False, True],[True, False, True]]) #error

original 2D:
 [[15 36 23]
 [ 9 35 13]
 [14 47 42]
 [ 9 41 27]]


IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 