In [4]:
#BROADCASTING AND RESHAPING...
import numpy as np
#1. broadcasting 
arr=np.array([3,5,1,0,7,6,3,4]) #[3,5,1,0,7,6,3,4]+[4,4,4,4,4,4,4,4]
print(arr+4)

arr2=np.array([[3,5,0,7],[6,3,4,1]]) 
print(arr2+2) #[[2,2,2,2],[2,2,2,2]] is added actually

[ 7  9  5  4 11 10  7  8]
[[5 7 2 9]
 [8 5 6 3]]


In [5]:
#1D and 2D arrays are taken
a1=np.array([3,5,4,7])
a2=np.array([
    [0,3,2,1],
    [2,4,5,3],
    [1,7,8,9]])
# 3 5 4 7     0 3 2 1
# 3 5 4 7  +  2 4 5 3
# 3 5 4 7     1 7 8 9
print(a1+a2) #add 1d row array in all rows of 2d arrays

[[ 3  8  6  8]
 [ 5  9  9 10]
 [ 4 12 12 16]]


In [7]:
#2D arrays are taken
a3=np.array([[3],
             [5],
             [4]])
# 3 3 3 3   0 3 2 1
# 5 5 5 5 + 2 4 5 3
# 4 4 4 4   1 7 8 9
print(a3+a2) #add 2d col array in all cols of  2d array.

[[ 3  6  5  4]
 [ 7  9 10  8]
 [ 5 11 12 13]]


In [9]:
# Error of Broadcasting
a4=np.array([1,2])
try:
    print(a2+a4)
except ValueError as e:
    print(e)
    

operands could not be broadcast together with shapes (3,4) (2,) 


In [11]:
#RESHAPPING....
#1. changing SHAPE Attribute...
arr=np.arange(12)
print("Array",arr)
print("Dimenson",arr.ndim)
print("Shape",arr.shape)

Array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Dimenson 1
Shape (12,)


In [16]:
arr.shape =(4,3)
print("Array \n",arr)
print("Dimenson",arr.ndim)
print("Shape",arr.shape)

Array 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Dimenson 2
Shape (4, 3)


In [17]:
arr.shape =(3,4) 
print("Array \n",arr)
print("Dimenson",arr.ndim)
print("Shape",arr.shape)

Array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Dimenson 2
Shape (3, 4)


In [19]:
#2. RESHAPE(array, shape)
arr1=np.arange(9)
print("Array",arr1)
print("Dimenson",arr1.ndim)
print("Shape",arr1.shape)

Array [0 1 2 3 4 5 6 7 8]
Dimenson 1
Shape (9,)


In [30]:
a2=np.reshape(arr1, (3,3)) #not InPlace creates a shallow copy of original
print("Array\n",a2)
print("Dimenson",a2.ndim)
print("Shape",a2.shape)

a2[2][2]=99
print("Array\n",arr1) #that means changes will be made in both 
print("Array\n",a2)


Array
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7 99]]
Dimenson 2
Shape (3, 3)
Array
 [ 0  1  2  3  4  5  6  7 99]
Array
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7 99]]


In [32]:
a3=np.reshape(arr,(2,3,2)) #more than one levels
print("Array\n",a3)
print("Dimenson",a3.ndim)
print("Shape",a3.shape)

Array
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
Dimenson 3
Shape (2, 3, 2)


In [27]:
#flattening of array by shape =-1
mat=np.array([[2,3],[4,5],[6,7]])
a4=np.reshape(mat,-1) #passing -1 as shape arg
print("flatten array:\n",a4)
print("Shape",a4.shape)
print("Dimenson",a4.ndim)

flatten array:
 [2 3 4 5 6 7]
Shape (6,)
Dimenson 1


In [35]:

#reshapping to incompatible shape/size
print(np.reshape(arr1, (3,2))) #raise error


ValueError: cannot reshape array of size 9 into shape (3,2)

In [39]:
#3. RESIZE(arr, newshape)
#MAJOR DIFF -> not raise error for incompatible shapes
print(arr1)
a6=np.resize(arr1, (3,2))
print(a6) # not raise error


a6[2][1]=66 #creates a deep copy object so change in one will not effect other
print(arr1)
print(a6)

[ 0  1  2  3  4  5  6  7 99]
[[0 1]
 [2 3]
 [4 5]]
[ 0  1  2  3  4  5  6  7 99]
[[ 0  1]
 [ 2  3]
 [ 4 66]]


In [41]:
#Experiments....
newa=np.array([1,2,3,4,5,6])
new=np.resize(newa,(4,4)) #by repeating elements from start to end until the required shape is filled
print("New Resized into bigger shape:\n", new)

new1=np.resize(newa,(2,2)) #by repeating elements from start to end until the required shape is filled
print("New Resized into bigger shape:\n", new1)

New Resized into bigger shape:
 [[1 2 3 4]
 [5 6 1 2]
 [3 4 5 6]
 [1 2 3 4]]
New Resized into bigger shape:
 [[1 2]
 [3 4]]


In [42]:
#4. Transpose()  ->called from array obh not from np
ta=np.array([[1,2,3,4],[5,6,7,8]])
ta2=ta.transpose()
print(ta2)

ta[1][2]=99

print(ta)
print(ta2)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[ 1  2  3  4]
 [ 5  6 99  8]]
[[ 1  5]
 [ 2  6]
 [ 3 99]
 [ 4  8]]


In [54]:
#5. SWAPAXES(arr, axis1, axis2)
sarr=np.arange(9).reshape(3,3)
print("Original: \n", sarr)

ns= np.swapaxes(sarr, 1,0)
print("New 0,1: \n", ns)
print("New 1,0: \n", np.swapaxes(sarr, 0,1)) #will transpose basically

Original: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
New 0,1: 
 [[0 3 6]
 [1 4 7]
 [2 5 8]]
New 1,0: 
 [[0 3 6]
 [1 4 7]
 [2 5 8]]


In [66]:
#3D Array Swapping...
s3arr=np.arange(18).reshape(2,3,3)
print("Original: \n", s3arr, "\nShape : ", s3arr.shape)

Original: 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]] 
Shape :  (2, 3, 3)


In [67]:
sht=np.swapaxes(s3arr, 0,1)
#levels are swapped with rows (3 new levels each with ith row from 2 old levels )
#level 1-> 1st row of level 1 and row 1st of level 2
#level 2-> 2nd row of level 1 + 2nd row of level 2
#level 3-> 3rd row of level 1\= 2nd row of level 2
print("New 3d swap axes: \n", sht, "\nShape: ", sht.shape) #swap rows in levels

New 3d swap axes: 
 [[[ 0  1  2]
  [ 9 10 11]]

 [[ 3  4  5]
  [12 13 14]]

 [[ 6  7  8]
  [15 16 17]]] 
Shape:  (3, 2, 3)


In [68]:
print("Original: \n", s3arr) 

sw3= np.swapaxes(s3arr, 0,2)
#levels are swapped with cols (3 new levels each with ith col from 2 old levels )
print("New 3d swap axes: \n",sw3, "\nShape: ", sw3.shape) #swap cols of levels

Original: 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
New 3d swap axes: 
 [[[ 0  9]
  [ 3 12]
  [ 6 15]]

 [[ 1 10]
  [ 4 13]
  [ 7 16]]

 [[ 2 11]
  [ 5 14]
  [ 8 17]]] 
Shape:  (3, 3, 2)


In [62]:
print("Original: \n", s3arr)
print("New 3d swap axes: \n", np.swapaxes(s3arr, 1,2))
# row and cols with in a level will be swapped within levels

Original: 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
New 3d swap axes: 
 [[[ 0  3  6]
  [ 1  4  7]
  [ 2  5  8]]

 [[ 9 12 15]
  [10 13 16]
  [11 14 17]]]


In [70]:
#6. FALLTTEN(order='C'/'F')
farr=np.arange(12).reshape(3,4)
print(farr)

nf= farr.flatten()
print("Row Major Flatten:\n", nf)


nfc= farr.flatten(order='F')
print("Row Major Flatten:\n", nfc)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Row Major Flatten:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Row Major Flatten:
 [ 0  4  8  1  5  9  2  6 10  3  7 11]


In [71]:
#7. SORT(arr, axis=None)
#1d sort
sort=np.sort(nfc)
print(sort)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [83]:
#2d sort
srarr=np.random.randint(1,50,(3,3))
print(srarr)

[[48  1 38]
 [25 29 15]
 [ 3 37 31]]


In [84]:
sort1=np.sort(srarr, axis=None)
print("No Axis",sort1) #no axis passed so flatten the array and sort in ascending order

sortX=np.sort(srarr, axis=0) #sort each column separately
print("Axis 0: \n",sortX) #axis 0 s0

sortY=np.sort(srarr, axis=1) #sort each row separate;
print("Axis 1: \n", sortY) #axis 1 so

No Axis [ 1  3 15 25 29 31 37 38 48]
Axis 0: 
 [[ 3  1 15]
 [25 29 31]
 [48 37 38]]
Axis 1: 
 [[ 1 38 48]
 [15 25 29]
 [ 3 31 37]]


In [87]:
#ITERATION...
#1d
iarr=np.random.randint(1,50,10)
print(iarr)
for i in iarr:
    print(i, end=",")

[13 37 32 39 35 48 29 12  7  6]
13,37,32,39,35,48,29,12,7,6,

In [94]:
#2d
i2arr=np.random.randint(1,50,(3,3))
print(i2arr)
for i in i2arr: #iterated over first axis of tuple in this case row->3
    print("iteration:")
    print(i)

[[31 38 34]
 [28 44 26]
 [ 7  8 19]]
iteration:
[31 38 34]
iteration:
[28 44 26]
iteration:
[ 7  8 19]


In [96]:
#2d
i3arr=np.random.randint(1,50,(2,3,3))
print(i3arr)
for i in i3arr: #level by level #iterated over first axis of tuple in this case level->2
    print("iteration:")
    print(i)

[[[17  2 15]
  [ 8 25 16]
  [47  7 44]]

 [[28 47  4]
  [ 5 31  3]
  [ 2  7 36]]]
iteration:
[[17  2 15]
 [ 8 25 16]
 [47  7 44]]
iteration:
[[28 47  4]
 [ 5 31  3]
 [ 2  7 36]]
