In [1]:
#MODIFYING NUMPY ARRAYS....
import numpy as np

In [2]:
#1 UPDATE EXISTING ARRAYS....
#1D ....
a1=np.random.randint(1,100,10)
print("Original array: ", a1)

#update...
a1[4]=99
a1[-2]=55

print("Updated array: ", a1)

Original array:  [33 27 57 94 49 27 35  4 84 18]
Updated array:  [33 27 57 94 99 27 35  4 55 18]


In [5]:
#2D ....
a2=np.random.randint(50,99,(4,3))
print("Original array: \n", a2)

#update...
a2[-1,-2]=999
a2[-2,1]=555

print("Updated array: \n", a2)

Original array: 
 [[78 77 82]
 [70 87 89]
 [80 80 97]
 [53 77 59]]
Updated array: 
 [[ 78  77  82]
 [ 70  87  89]
 [ 80 555  97]
 [ 53 999  59]]


In [7]:
#3D ....
a3=np.random.randint(1,50,(2,3,3))
print("Original array: \n", a3)

#update...
a3[-1,-2,-3]=999
a3[0,2,2]=555

print("Updated array: \n", a3)

Original array: 
 [[[ 9 32  6]
  [22 36  7]
  [13 31  7]]

 [[ 1 37 32]
  [21 48 45]
  [ 2 47 31]]]
Updated array: 
 [[[  9  32   6]
  [ 22  36   7]
  [ 13  31 555]]

 [[  1  37  32]
  [999  48  45]
  [  2  47  31]]]


In [12]:
#1 APPEND EXISTING ARRAYS....

#np.append(arr, values, axis) ->axis not given then flattens arr and values and add at end.
#1D ....
print("Old array: ", a1)
arr2=np.append(a1,[12, 43,21])
print("1D After Append array: ", arr2)

#SHALLOW COPY...
print(id(a1),id(arr2)) #different returns a new arrays with appended values

Old array:  [33 27 57 94 99 27 35  4 55 18]
After Append array:  [33 27 57 94 99 27 35  4 55 18 12 43 21]
2362031091760 2362069657712


In [25]:
#2D ....
print("Old array: \n", a2)
#append new row at the end of rows aix=0
arr1=np.append(a2,[[12, 43,21]], axis=0)  
print("2D After Row Append array:\n ", arr1)

#append new col at the end of cols axis=1
arr=np.append(arr1,[[12],[43],[21],[55],[66]], axis=1)  
print("2D After Col Append array:\n ", arr)

Old array: 
 [[ 78  77  82]
 [ 70  87  89]
 [ 80 555  97]
 [ 53 999  59]]
2D After Row Append array:
  [[ 78  77  82]
 [ 70  87  89]
 [ 80 555  97]
 [ 53 999  59]
 [ 12  43  21]]
2D After Col Append array:
  [[ 78  77  82  12]
 [ 70  87  89  43]
 [ 80 555  97  21]
 [ 53 999  59  55]
 [ 12  43  21  66]]


In [20]:
#PROOF OF CENCEPT (no axis given flatten the array and values)
ar=np.append(arr,[[12],[43],[21],[55],[66]])  
print("2D After Append array:\n ", ar)

2D After Append array:
  [ 78  77  82  12  70  87  89  43  80 555  97  21  53 999  59  55  12  43
  21  66  12  43  21  55  66]


In [27]:
#3D ....
print("Original array: \n", a3)

#APPENDING NEW LEVEL
arr3=np.append(a3, [[[0,1,2],[3,4,5],[6,7,8]]], axis=0)
print("After axis=0 append array: \n", arr3)

Original array: 
 [[[  9  32   6]
  [ 22  36   7]
  [ 13  31 555]]

 [[  1  37  32]
  [999  48  45]
  [  2  47  31]]]
After axis=0 append array: 
 [[[  9  32   6]
  [ 22  36   7]
  [ 13  31 555]]

 [[  1  37  32]
  [999  48  45]
  [  2  47  31]]

 [[  0   1   2]
  [  3   4   5]
  [  6   7   8]]]


In [37]:
#APPENDING NEW ROW
arr4=np.append(arr3,[[[88,77,22]],[[88,77,66]],[[88,77,66]]], axis=1)
print("After axis=1 append array: \n", arr4)

After axis=1 append array: 
 [[[  9  32   6]
  [ 22  36   7]
  [ 13  31 555]
  [ 88  77  22]]

 [[  1  37  32]
  [999  48  45]
  [  2  47  31]
  [ 88  77  66]]

 [[  0   1   2]
  [  3   4   5]
  [  6   7   8]
  [ 88  77  66]]]


In [38]:
#APPENDING NEW COL
arr5=np.append(arr4,[[[11],[33],[22],[44]],[[11],[33],[22],[44]],[[11],[33],[22],[44]]], axis=2)
print("After axis=2 append array: \n", arr5)

After axis=2 append array: 
 [[[  9  32   6  11]
  [ 22  36   7  33]
  [ 13  31 555  22]
  [ 88  77  22  44]]

 [[  1  37  32  11]
  [999  48  45  33]
  [  2  47  31  22]
  [ 88  77  66  44]]

 [[  0   1   2  11]
  [  3   4   5  33]
  [  6   7   8  22]
  [ 88  77  66  44]]]


In [40]:
#3. INSERT IN ARRAYS...
#1D np.insert(arr, index, values)

print("Before Insert:\n ", ar)
ar1=np.insert(ar, -5, 1000)
print("After 1D Insert at -5:\n ", ar1)

Before Insert:
  [ 78  77  82  12  70  87  89  43  80 555  97  21  53 999  59  55  12  43
  21  66  12  43  21  55  66]
After 1D Insert at -5:
  [  78   77   82   12   70   87   89   43   80  555   97   21   53  999
   59   55   12   43   21   66 1000   12   43   21   55   66]


In [48]:
#2D np.insert(arr, index, values, axis=None)
print("Old array: \n", a2)
ar2=np.insert(a2, -2, [0,1,2], axis=0) #insert after the specified index here after -2 at -3
print("After 2D Insert at axis=0:\n ", ar2)

ar3=np.insert(ar2, -2, [0,1,2,3,4], axis=1) #insert after the specified index here after -2 at -3
print("After 2D Insert at axis=1:\n ", ar3)

Old array: 
 [[ 78  77  82]
 [ 70  87  89]
 [ 80 555  97]
 [ 53 999  59]]
After 2D Insert at axis=0:
  [[ 78  77  82]
 [ 70  87  89]
 [  0   1   2]
 [ 80 555  97]
 [ 53 999  59]]
After 2D Insert at axis=1:
  [[ 78   0  77  82]
 [ 70   1  87  89]
 [  0   2   1   2]
 [ 80   3 555  97]
 [ 53   4 999  59]]


In [65]:
#2D BROADCAST SINGLE VALUE ON AXIS...
print("Old array: \n", a2)
aar2=np.insert(a2, 2, 55, axis=0) 
print("After 2D Insert at axis=0:\n ", aar2)

aar3=np.insert(aar2, 2, 66, axis=1) 
print("After 2D Insert at axis=1:\n ", aar3)

Old array: 
 [[ 78  77  82]
 [ 70  87  89]
 [ 80 555  97]
 [ 53 999  59]]
After 2D Insert at axis=0:
  [[ 78  77  82]
 [ 70  87  89]
 [ 55  55  55]
 [ 80 555  97]
 [ 53 999  59]]
After 2D Insert at axis=1:
  [[ 78  77  66  82]
 [ 70  87  66  89]
 [ 55  55  66  55]
 [ 80 555  66  97]
 [ 53 999  66  59]]


In [50]:
#3D np.insert(arr, index, values)
#LEVEL INSERT
print("Original array: \n", a3)
ar4=np.insert(a3, -1,[[[0,1,2],[3,4,5],[6,7,8]]] ,axis=0) #after -1 level added this new level
print("Insert on 3d at axis=0 array: \n", ar4)

Original array: 
 [[[  9  32   6]
  [ 22  36   7]
  [ 13  31 555]]

 [[  1  37  32]
  [999  48  45]
  [  2  47  31]]]
Insert on 3d at axis=0 array: 
 [[[  9  32   6]
  [ 22  36   7]
  [ 13  31 555]]

 [[  0   1   2]
  [  3   4   5]
  [  6   7   8]]

 [[  1  37  32]
  [999  48  45]
  [  2  47  31]]]


In [55]:
#ROW INSERT
print("Old array: \n", ar4)
ar6=np.insert(ar4, 1, [[11,12,13],[14,15,16],[17,18,19]],axis=1) #different row for all diff levels
ar5=np.insert(ar4, 1, [17,18,19],axis=1)#single row added in all levels
print("Insert on 3d at axis=1 array: \n", ar5)
print("Insert on 3d at axis=1 array: \n", ar6)

Old array: 
 [[[  9  32   6]
  [ 22  36   7]
  [ 13  31 555]]

 [[  0   1   2]
  [  3   4   5]
  [  6   7   8]]

 [[  1  37  32]
  [999  48  45]
  [  2  47  31]]]
Insert on 3d at axis=1 array: 
 [[[  9  32   6]
  [ 17  18  19]
  [ 22  36   7]
  [ 13  31 555]]

 [[  0   1   2]
  [ 17  18  19]
  [  3   4   5]
  [  6   7   8]]

 [[  1  37  32]
  [ 17  18  19]
  [999  48  45]
  [  2  47  31]]]
Insert on 3d at axis=1 array: 
 [[[  9  32   6]
  [ 11  12  13]
  [ 22  36   7]
  [ 13  31 555]]

 [[  0   1   2]
  [ 14  15  16]
  [  3   4   5]
  [  6   7   8]]

 [[  1  37  32]
  [ 17  18  19]
  [999  48  45]
  [  2  47  31]]]


In [57]:
#COL INSERT
ar7=np.insert(ar5, 2, [22,33,44,55],axis=2) 
ar8=np.insert(ar6, 2, [[99,88,77,66],[55,44,33,22],[33,22,11,10]], axis=2)
print("Insert on 3d at axis=2 single col array: \n", ar7)
print("Insert on 3d at axis=2 diff col array: \n", ar8)

Insert on 3d at axis=2 single col array: 
 [[[  9  32  22   6]
  [ 17  18  33  19]
  [ 22  36  44   7]
  [ 13  31  55 555]]

 [[  0   1  22   2]
  [ 17  18  33  19]
  [  3   4  44   5]
  [  6   7  55   8]]

 [[  1  37  22  32]
  [ 17  18  33  19]
  [999  48  44  45]
  [  2  47  55  31]]]
Insert on 3d at axis=2 diff col array: 
 [[[  9  32  99   6]
  [ 11  12  88  13]
  [ 22  36  77   7]
  [ 13  31  66 555]]

 [[  0   1  55   2]
  [ 14  15  44  16]
  [  3   4  33   5]
  [  6   7  22   8]]

 [[  1  37  33  32]
  [ 17  18  22  19]
  [999  48  11  45]
  [  2  47  10  31]]]


In [66]:
#DELETE ARRAYS...
#1D  delete(arr, index)
print("Original:\n ", ar1)
d1=np.delete(ar1, -7) #SINGLE VALUE 
print("After deleting from -7:\n ", d1) #66 is deleted

dd1=np.delete(d1, [6,-3, 2]) #MULTIPLE VALUES BY INDEXES... 
print("After deleting from [6, -3, 2]:\n ", dd1) #66 is deleted

Original:
  [  78   77   82   12   70   87   89   43   80  555   97   21   53  999
   59   55   12   43   21   66 1000   12   43   21   55   66]
After deleting from -7:
  [  78   77   82   12   70   87   89   43   80  555   97   21   53  999
   59   55   12   43   21 1000   12   43   21   55   66]
After deleting from -7:
  [  78   77   12   70   87   43   80  555   97   21   53  999   59   55
   12   43   21 1000   12   43   55   66]


In [62]:
#2D  delete(arr, index, axis=None)
print("Old array: \n", a2)

#Row at index 2 will be deleted
d2=np.delete(a2,2,axis=0) 
print("After deleting row at 2:\n ", d2)


#Col at index 2 will be deleted
d3=np.delete(a2,2,axis=1) 
print("After deleting col at 2:\n ", d3)

Old array: 
 [[ 78  77  82]
 [ 70  87  89]
 [ 80 555  97]
 [ 53 999  59]]
After deleting row at 2:
  [[ 78  77  82]
 [ 70  87  89]
 [ 53 999  59]]
After deleting col at 2:
  [[ 78  77]
 [ 70  87]
 [ 80 555]
 [ 53 999]]


In [69]:
#MUTTIPLE ROW AND COLS DELETE...
#ROWS...
dd2=np.delete(a2, [1,3], axis=0)
print("Multi Rows Delete\n", dd2)


#COLS..
dd3=np.delete(a2, [0,2], axis=1)
print("Multi Cols Delete\n", dd3)

Multi Rows Delete
 [[ 78  77  82]
 [ 80 555  97]]
Multi Cols Delete
 [[ 77]
 [ 87]
 [555]
 [999]]


In [71]:
#3D  delete(arr, index, axis=None)
#LEVELS....
#SINGLE
print("Original: \n", ar8)
d4=np.delete(ar8, 1, axis=0)
print("After deleting level at 1:\n ", d4)

#MULTIPLE....
d5=np.delete(ar8, [0,2], axis=0)
print("After deleting level at [0,2]:\n ", d5)

Original: 
 [[[  9  32  99   6]
  [ 11  12  88  13]
  [ 22  36  77   7]
  [ 13  31  66 555]]

 [[  0   1  55   2]
  [ 14  15  44  16]
  [  3   4  33   5]
  [  6   7  22   8]]

 [[  1  37  33  32]
  [ 17  18  22  19]
  [999  48  11  45]
  [  2  47  10  31]]]
After deleting level at 1:
  [[[  9  32  99   6]
  [ 11  12  88  13]
  [ 22  36  77   7]
  [ 13  31  66 555]]

 [[  1  37  33  32]
  [ 17  18  22  19]
  [999  48  11  45]
  [  2  47  10  31]]]
After deleting level at [0,2]:
  [[[ 0  1 55  2]
  [14 15 44 16]
  [ 3  4 33  5]
  [ 6  7 22  8]]]


In [72]:
#ROWS....
#SINGLE
print("Original: \n", ar8)
d6=np.delete(ar8, 3, axis=1)
print("Deleting Row at 3:\n ", d6)

#MULTIPLE....
d7=np.delete(ar8, [1,2], axis=1)
print("Deleting Row at [0,2]:\n ", d7)

Original: 
 [[[  9  32  99   6]
  [ 11  12  88  13]
  [ 22  36  77   7]
  [ 13  31  66 555]]

 [[  0   1  55   2]
  [ 14  15  44  16]
  [  3   4  33   5]
  [  6   7  22   8]]

 [[  1  37  33  32]
  [ 17  18  22  19]
  [999  48  11  45]
  [  2  47  10  31]]]
Deleting Row at 3:
  [[[  9  32  99   6]
  [ 11  12  88  13]
  [ 22  36  77   7]]

 [[  0   1  55   2]
  [ 14  15  44  16]
  [  3   4  33   5]]

 [[  1  37  33  32]
  [ 17  18  22  19]
  [999  48  11  45]]]
Deleting Row at [0,2]:
  [[[  9  32  99   6]
  [ 13  31  66 555]]

 [[  0   1  55   2]
  [  6   7  22   8]]

 [[  1  37  33  32]
  [  2  47  10  31]]]


In [75]:
#COLS....
#SINGLE
print("Original: \n", ar8)
d8=np.delete(ar8, 2, axis=2)
print("Deleting Col at 2:\n ", d8)

#MULTIPLE....
#SLICING...
d9=np.delete(ar8, np.s_[::2] , axis=2)
print("Deleting Cols at np.s_[::2]:\n ", d9)

d10=np.delete(ar8, slice(1,3) , axis=2)
print("Deleting Cols at slice(1,3):\n ", d10)

Original: 
 [[[  9  32  99   6]
  [ 11  12  88  13]
  [ 22  36  77   7]
  [ 13  31  66 555]]

 [[  0   1  55   2]
  [ 14  15  44  16]
  [  3   4  33   5]
  [  6   7  22   8]]

 [[  1  37  33  32]
  [ 17  18  22  19]
  [999  48  11  45]
  [  2  47  10  31]]]
Deleting Col at 2:
  [[[  9  32   6]
  [ 11  12  13]
  [ 22  36   7]
  [ 13  31 555]]

 [[  0   1   2]
  [ 14  15  16]
  [  3   4   5]
  [  6   7   8]]

 [[  1  37  32]
  [ 17  18  19]
  [999  48  45]
  [  2  47  31]]]
Deleting Cols at np.s_[::2]:
  [[[ 32   6]
  [ 12  13]
  [ 36   7]
  [ 31 555]]

 [[  1   2]
  [ 15  16]
  [  4   5]
  [  7   8]]

 [[ 37  32]
  [ 18  19]
  [ 48  45]
  [ 47  31]]]
Deleting Cols at slice(1,3):
  [[[  9   6]
  [ 11  13]
  [ 22   7]
  [ 13 555]]

 [[  0   2]
  [ 14  16]
  [  3   5]
  [  6   8]]

 [[  1  32]
  [ 17  19]
  [999  45]
  [  2  31]]]


In [77]:
#5. ALIASING/COPYING ARRAYS....
#Aliasing...
aa=np.random.randint(4,44,10)
print(aa)
aa1=aa
print(aa1)
print(id(aa), id(aa1))  #same ids so aliases..



#updation in both cause at backend only one object
aa[-3] =99 
print(aa)
print(aa1)

[34  6  4 32 33 38 35 18 27 31]
[34  6  4 32 33 38 35 18 27 31]
2362077132816 2362077132816
[34  6  4 32 33 38 35 99 27 31]
[34  6  4 32 33 38 35 99 27 31]


In [78]:
#SHALLOW COPY...
#which is just a view in case of NumPy Arrays...
aa2=aa[:]

print(aa)
print(aa2)
print(id(aa), id(aa2))  #DIFFERENT Ids cause at backend they are diff objects in memory

#Updation...
aa2[4]=1001  #but changes will be made in both cause its just a view to show 
print(aa)
print(aa2)

[34  6  4 32 33 38 35 99 27 31]
[34  6  4 32 33 38 35 99 27 31]
2362077132816 2362071607600
[  34    6    4   32 1001   38   35   99   27   31]
[  34    6    4   32 1001   38   35   99   27   31]


In [79]:
#DEEP COPY
#do the real task of creating a new array at backend in memory and changes will not be made in both
aa3=aa.copy()

print(aa)
print(aa3)
print(id(aa), id(aa3))  #DIFFERENT Ids cause at backend they have diff memory locations

aa3[5]=9999 #Changes made in only the mentioned one 
print(aa)
print(aa3)


[  34    6    4   32 1001   38   35   99   27   31]
[  34    6    4   32 1001   38   35   99   27   31]
2362077132816 2362071607504
[  34    6    4   32 1001   38   35   99   27   31]
[  34    6    4   32 1001 9999   35   99   27   31]
