In [1]:
#1.CONCATENATION......
import numpy as np

In [4]:
#1D Concatenate...
arr1=np.random.randint(5,50,15)
arr2=np.random.randint(1,10,5)
print("Array 1: ",arr1)
print("Array 2: ",arr2)

#concate
arr3=np.concatenate((arr1,arr2))
print("Concatenated Array: ",arr3)
arr3=np.concatenate((arr1,arr2),axis=0)
print("Concatenated Array: ",arr3)

Array 1:  [33 34 49  5 36 28 44 36 27 33 28  6 44 18 13]
Array 2:  [2 6 5 4 7]
Concatenated Array:  [33 34 49  5 36 28 44 36 27 33 28  6 44 18 13  2  6  5  4  7]
Concatenated Array:  [33 34 49  5 36 28 44 36 27 33 28  6 44 18 13  2  6  5  4  7]


In [13]:
#2D Concatenate along axis=0
arr4=np.random.randint(1,50,(2,3))
arr5=np.random.randint(1,50,(3,3))
#arr5=np.random.randint(1,50,(3,4))  #ERROR of mismatched Columns
print("2D Array 1:\n ",arr4)
print("2D Array 2: \n",arr5)


#concatenate along axis=0  
arr6=np.concatenate((arr4,arr5), axis=0)  #No. of Columns must be same for vertical concatenation
print("2D Concatenated Array: \n",arr6)

2D Array 1:
  [[46 19 27]
 [31 37 29]]
2D Array 2: 
 [[46 35 18]
 [45 34 33]
 [28 13  2]]
2D Concatenated Array: 
 [[46 19 27]
 [31 37 29]
 [46 35 18]
 [45 34 33]
 [28 13  2]]


In [15]:
#2D Concatenate along axis=1
arr7=np.random.randint(1,50,(2,3))
arr8=np.random.randint(1,50,(2,4))
#arr8=np.random.randint(1,50,(3,4)) #ERROR of mismatched Rows
print("2D Array 1:\n ",arr7)
print("2D Array 2: \n",arr8)


#concatenate along axis=0  
arr9=np.concatenate((arr7,arr8), axis=1)  #No. of Rows must be same for Horizontal concatenation
print("2D Horizontal Concatenated Array: \n",arr9)

2D Array 1:
  [[ 6 41 39]
 [31 16 34]]
2D Array 2: 
 [[43 18 48 15]
 [21 48 31 20]]
2D Horizontal Concatenated Array: 
 [[ 6 41 39 43 18 48 15]
 [31 16 34 21 48 31 20]]


In [26]:
#3D Concatenate along axis=0
arr10=np.random.randint(1,50,(2,3,2))
arr11=np.random.randint(1,50,(3,3,2))
print("3D Array 1:\n ",arr10)
print("3D Array 2: \n",arr11)


#concatenate along axis=0  
arr12=np.concatenate((arr10,arr11), axis=0)  #No. of ROWs and COls in both Arrays must match 
print("3D Level Concatenated Array: \n",arr12)

3D Array 1:
  [[[20 19]
  [ 9 46]
  [36 23]]

 [[47  1]
  [49 21]
  [34  4]]]
3D Array 2: 
 [[[30 39]
  [ 6 16]
  [13 43]]

 [[34 38]
  [21 10]
  [29 11]]

 [[22 14]
  [38 21]
  [ 9 46]]]
3D Level Concatenated Array: 
 [[[20 19]
  [ 9 46]
  [36 23]]

 [[47  1]
  [49 21]
  [34  4]]

 [[30 39]
  [ 6 16]
  [13 43]]

 [[34 38]
  [21 10]
  [29 11]]

 [[22 14]
  [38 21]
  [ 9 46]]]


In [27]:
#3D Concatenate along axis=1  
arr14=np.random.randint(1,50,(2,3,2))
arr15=np.random.randint(1,50,(2,2,2))
print("3D Array 1:\n ",arr14)
print("3D Array 2: \n",arr15)

#No. of Levels and  Colums must match in both arrays
arr13=np.concatenate((arr14,arr15), axis=1)  
print("3D Row Concatenated Array: \n",arr13)

3D Array 1:
  [[[18 22]
  [21 39]
  [ 5 17]]

 [[39 48]
  [31  6]
  [ 8 23]]]
3D Array 2: 
 [[[43 44]
  [15  9]]

 [[49 45]
  [35 29]]]
3D Row Concatenated Array: 
 [[[18 22]
  [21 39]
  [ 5 17]
  [43 44]
  [15  9]]

 [[39 48]
  [31  6]
  [ 8 23]
  [49 45]
  [35 29]]]


In [28]:
#3D Concatenate along axis=2  
arr17=np.random.randint(1,50,(2,3,2))
arr18=np.random.randint(1,50,(2,3,3))
print("3D Array 1:\n ",arr17)
print("3D Array 2: \n",arr18)

#No. of Levels and  Rows must match in both arrays
arr19=np.concatenate((arr17,arr18), axis=2)  
print("3D Col Concatenated Array: \n",arr19)

3D Array 1:
  [[[26 42]
  [17 41]
  [16 17]]

 [[ 3  6]
  [37 40]
  [44 32]]]
3D Array 2: 
 [[[32 32 39]
  [25 17 11]
  [49 32 22]]

 [[ 8 14  9]
  [17 29 47]
  [37 43  3]]]
3D Col Concatenated Array: 
 [[[26 42 32 32 39]
  [17 41 25 17 11]
  [16 17 49 32 22]]

 [[ 3  6  8 14  9]
  [37 40 17 29 47]
  [44 32 37 43  3]]]


In [41]:
#2. STACKING.....
#1D vstack(tup)
sa1=np.random.randint(1,10,5)
sa2=np.random.randint(1,10,5)
print("Array 1:\n ",sa1)
print("Array 2:\n",sa2)

#No. cols/size in case of 1d must match
sa3=np.vstack((sa1,sa2))  
print("Stacked 1D Array: \n",sa3)

Array 1:
  [3 8 9 3 1]
Array 2:
 [2 7 2 1 9]
Stacked 1D Array: 
 [[3 8 9 3 1]
 [2 7 2 1 9]]


In [42]:
#2D vstack(tup)
sa4=np.random.randint(1,20,(3,4))
sa5=np.random.randint(1,20,(4,4))
print("2d Array 1:\n ",sa4)
print("2d Array 2:\n",sa5)

#No. cols in case of 2d must match
sa6=np.vstack((sa4,sa5))  
print("Stacked 2D Array: \n",sa6)

2d Array 1:
  [[11  7 10 13]
 [18 18  5 15]
 [ 4  8  1  9]]
2d Array 2:
 [[ 5 18  7 13]
 [17 16 11 12]
 [16  9  5 16]
 [ 7 18 19 14]]
Stacked 2D Array: 
 [[11  7 10 13]
 [18 18  5 15]
 [ 4  8  1  9]
 [ 5 18  7 13]
 [17 16 11 12]
 [16  9  5 16]
 [ 7 18 19 14]]


In [38]:
#3D vstack(tup)
sa7=np.random.randint(1,20,(2,3,2))
sa8=np.random.randint(1,20,(3,3,2))
print("3d Array 1:\n ",sa7)
print("3d Array 2:\n",sa8)

#No. rows and cols in case of 3d must match
sa9=np.vstack((sa7,sa8))  
print("Stacked 3D Array: \n",sa9)

3d Array 1:
  [[[ 3  5]
  [12  6]
  [16 10]]

 [[ 1 14]
  [ 3 12]
  [ 2  7]]]
3d Array 2:
 [[[19  6]
  [19 10]
  [ 1 12]]

 [[ 9  2]
  [18 15]
  [ 6  5]]

 [[19  8]
  [12  8]
  [ 8 15]]]
Stacked 3D Array: 
 [[[ 3  5]
  [12  6]
  [16 10]]

 [[ 1 14]
  [ 3 12]
  [ 2  7]]

 [[19  6]
  [19 10]
  [ 1 12]]

 [[ 9  2]
  [18 15]
  [ 6  5]]

 [[19  8]
  [12  8]
  [ 8 15]]]


In [40]:
#1D hstack(tup)...
s1=np.random.randint(1,10,5)
s2=np.random.randint(1,10,8)
print("1d Array 1:\n ",s1)
print("1d Array 2:\n",s2)

#No. cols/size can vary
s3=np.hstack((s1,s2))  
print("Horizontal Stacked 1D Array: \n",s3)

1d Array 1:
  [4 7 3 4 4]
1d Array 2:
 [9 8 7 6 6 4 8 4]
Horizontal Stacked 1D Array: 
 [4 7 3 4 4 9 8 7 6 6 4 8 4]


In [44]:
#2D hstack(tup)
s4=np.random.randint(1,20,(3,4))
s5=np.random.randint(1,20,(3,2))
print("2D Array 1:\n ",s4)
print("2D Array 2:\n",s5)

#No. Rows in case of 2d must match
s6=np.hstack((s4,s5))  
print("Horizontal Stacked 2D Array: \n",s6)

2D Array 1:
  [[ 6 16  9 16]
 [16 18  5 16]
 [12 19 19  5]]
2D Array 2:
 [[ 7  7]
 [11  6]
 [10  6]]
Horizontal Stacked 2D Array: 
 [[ 6 16  9 16  7  7]
 [16 18  5 16 11  6]
 [12 19 19  5 10  6]]


In [53]:
#3D hstack(tup)
s7=np.random.randint(1,20,(2,3,2))
s8=np.random.randint(1,20,(2,2,2))
print("3d Array 1:\n ",s7)
print("3d Array 2:\n",s8)

#No. Levels and cols in case of 3d must match
s9=np.hstack((s7,s8))  
print("Horizontal Stacked 3D Array: \n",s9)

3d Array 1:
  [[[14  6]
  [17 14]
  [16 12]]

 [[17  3]
  [ 1  8]
  [ 2 18]]]
3d Array 2:
 [[[ 4  2]
  [14 14]]

 [[13 18]
  [15 14]]]
Horizontal Stacked 3D Array: 
 [[[14  6]
  [17 14]
  [16 12]
  [ 4  2]
  [14 14]]

 [[17  3]
  [ 1  8]
  [ 2 18]
  [13 18]
  [15 14]]]


In [57]:
#Basic stack
#stack along a new axis alog with the given one...
#1D stack(tup, axis=0)
print("Array 1:\n ",sa1)
print("Array 2:\n",sa2)

#along axis=0 sizes must be same...
st=np.stack((sa1,sa2),axis=0)  
print("Stacked 1D Array at axis=0: \n",st)

#along axis=1 sizes must be same...
st1=np.stack((sa1,sa2),axis=1)  
print("Stacked 1D Array at axis=1: \n",st1)

Array 1:
  [3 8 9 3 1]
Array 2:
 [2 7 2 1 9]
Stacked 1D Array at axis=0: 
 [[3 8 9 3 1]
 [2 7 2 1 9]]
Stacked 1D Array at axis=1: 
 [[3 2]
 [8 7]
 [9 2]
 [3 1]
 [1 9]]


In [68]:
#2D stack(tup, axis=0)
st4=np.random.randint(5,30,(2,3))
st5=np.random.randint(1,25,(2,3))
print("2d Array 1:\n ",st4)
print("2d Array 2:\n",st5)

#along axis=0 sizes must be same...
st2=np.stack((st4,st5),axis=0)  
print("Stacked 2D Array at axis=0: \n",st2)

#along axis=1 sizes must be same...
st3=np.stack((st4,st5),axis=1)  
print("Stacked 2D Array at axis=1: \n",st3)

#along axis=2 sizes must be same...
st6=np.stack((st4,st5),axis=-1) #axis=2 or axis=-1  are same 
print("Stacked 2D Array at axis=2: \n",st6)


2d Array 1:
  [[27 29  8]
 [14 24 21]]
2d Array 2:
 [[16  4 11]
 [ 4 19  9]]
Stacked 2D Array at axis=0: 
 [[[27 29  8]
  [14 24 21]]

 [[16  4 11]
  [ 4 19  9]]]
Stacked 2D Array at axis=1: 
 [[[27 29  8]
  [16  4 11]]

 [[14 24 21]
  [ 4 19  9]]]
Stacked 2D Array at axis=2: 
 [[[27 16]
  [29  4]
  [ 8 11]]

 [[14  4]
  [24 19]
  [21  9]]]


In [103]:
#3D stack(tup, axis=0)
st7=np.random.randint(5,30,(2,2,2))
st8=np.random.randint(1,25,(2,2,2))
print("2d Array 1:\n ",st7)
print("2d Array 2:\n",st8)

#along axis=0 sizes must be same...
st=np.stack((st7,st8),axis=0)  
print("Stacked 3D Array at axis=0: \n",st)

#along axis=1 sizes must be same...
st9=np.stack((st7,st8),axis=1)  
print("Stacked 3D Array at axis=1: \n",st9)


2d Array 1:
  [[[22 17]
  [ 8  7]]

 [[23  9]
  [13 10]]]
2d Array 2:
 [[[15  1]
  [23 15]]

 [[20 17]
  [10  3]]]
Stacked 3D Array at axis=0: 
 [[[[22 17]
   [ 8  7]]

  [[23  9]
   [13 10]]]


 [[[15  1]
   [23 15]]

  [[20 17]
   [10  3]]]]
Stacked 3D Array at axis=1: 
 [[[[22 17]
   [ 8  7]]

  [[15  1]
   [23 15]]]


 [[[23  9]
   [13 10]]

  [[20 17]
   [10  3]]]]
Stacked 3D Array at axis=2: 
 [[[[22 17]
   [15  1]]

  [[ 8  7]
   [23 15]]]


 [[[23  9]
   [20 17]]

  [[13 10]
   [10  3]]]]


In [74]:
#along axis=2 sizes must be same...
st10=np.stack((st7,st8),axis=2)
print("Stacked 3D Array at axis=2: \n",st10)


#along axis= sizes must be same...
st11=np.stack((st7,st8),axis=-1)  #axis=3 or -1 is same
print("Stacked 3D Array at axis=-1: \n",st11)


Stacked 3D Array at axis=2: 
 [[[[21  8]
   [ 8  1]]

  [[28 10]
   [17  9]]]


 [[[14 18]
   [14 23]]

  [[27 25]
   [24  7]]]]
Stacked 3D Array at axis=-1: 
 [[[[21  8]
   [ 8  1]]

  [[28 17]
   [10  9]]]


 [[[14 14]
   [18 23]]

  [[27 24]
   [25  7]]]]


In [77]:
#3. SPLITTING.....
#1D split(arr, size, axis=0)   --> array_aplit()
sp=np.random.randint(1,50,20)
print("1D Array:", sp)

#split in 4 equal parts if equal parts not possible will raise error
sp1=np.split(sp,4)
print("splits of 1d Array in equal :", sp1)

sp2=np.array_split(sp,3)
print("splits of 1d Array in non-equal:", sp2)

1D Array: [21 28 43 25 40 43 48 38  1  4 41 46 15 29 32 46 29 11 24 43]
splits of 1d Array in equal : [array([21, 28, 43, 25, 40]), array([43, 48, 38,  1,  4]), array([41, 46, 15, 29, 32]), array([46, 29, 11, 24, 43])]
splits of 1d Array in non-equal: [array([21, 28, 43, 25, 40, 43, 48]), array([38,  1,  4, 41, 46, 15, 29]), array([32, 46, 29, 11, 24, 43])]


In [80]:
#2D split(arr, size, axis=0)   --> array_aplit()
sp3=np.random.randint(1,50,(4,5))
print("2D Array:\n", sp3)

#split in 4 equal parts if equal parts not possible will raise error
sp4=np.array_split(sp3,3,axis=0)
print("splits of 2d Array on axis=0:\n", sp4)

sp5=np.array_split(sp3,3,axis=1)
print("splits of 2d Array on axis=1\n:", sp5)

2D Array:
 [[17 13 18 18 15]
 [44 36 38  5 43]
 [ 6 33 14 33  6]
 [36 34 13 28  8]]
splits of 2d Array on axis=0:
 [array([[17, 13, 18, 18, 15],
       [44, 36, 38,  5, 43]]), array([[ 6, 33, 14, 33,  6]]), array([[36, 34, 13, 28,  8]])]
splits of 2d Array on axis=1
: [array([[17, 13],
       [44, 36],
       [ 6, 33],
       [36, 34]]), array([[18, 18],
       [38,  5],
       [14, 33],
       [13, 28]]), array([[15],
       [43],
       [ 6],
       [ 8]])]


In [95]:
#3D split(arr, size, axis=0)   --> array_aplit()
sp6=np.random.randint(1,10,(2,2,3))
print("3D Array:\n", sp6)

#split in 4 equal parts if equal parts not possible will raise error
sp7=np.array_split(sp6,2,axis=0)
print("splits of 3d Array on axis=0:\n", sp7)

sp8=np.array_split(sp6,3,axis=1)
print("splits of 3d Array on axis=1\n:", sp8)

sp9=np.array_split(sp6,2,axis=2)
print("splits of 3d Array on axis=2\n:", sp9)

3D Array:
 [[[3 2 9]
  [6 9 8]]

 [[7 5 5]
  [4 8 6]]]
splits of 3d Array on axis=0:
 [array([[[3, 2, 9],
        [6, 9, 8]]]), array([[[7, 5, 5],
        [4, 8, 6]]])]
splits of 3d Array on axis=1
: [array([[[3, 2, 9]],

       [[7, 5, 5]]]), array([[[6, 9, 8]],

       [[4, 8, 6]]]), array([], shape=(2, 0, 3), dtype=int32)]
splits of 3d Array on axis=2
: [array([[[3, 2],
        [6, 9]],

       [[7, 5],
        [4, 8]]]), array([[[9],
        [8]],

       [[5],
        [6]]])]


In [102]:
#1d hsplit(arr, size)...
har=np.arange(16).reshape(4,4)
print("New 2d array: \n", har)

har1=np.hsplit(har, 2)
print("Hsplit 2d array: \n", har1)

har2=np.vsplit(har, 2)
print("Vsplit 2d array: \n", har2)

New 2d array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Hsplit 2d array: 
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
Vsplit 2d array: 
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
