In [1]:
#CREATING DATAFRAMES....
import numpy as np
import pandas as pd

In [3]:
#create from 2d numpy array...
arr=np.random.randint(10,100, (6,5))
df=pd.DataFrame(arr)
print(arr)
print(df)

[[15 88 89 25 56]
 [19 64 10 29 96]
 [63 50 25 68 49]
 [17 76 13 96 69]
 [38 82 58 71 51]
 [85 84 46 68 33]]
    0   1   2   3   4
0  15  88  89  25  56
1  19  64  10  29  96
2  63  50  25  68  49
3  17  76  13  96  69
4  38  82  58  71  51
5  85  84  46  68  33


In [5]:
df=pd.DataFrame(arr, index=["row1", "row2", "row3", "row4", "row5", "row6"], columns=["col1", "col2", "col3", "col4", "col5"])
print(df)

      col1  col2  col3  col4  col5
row1    15    88    89    25    56
row2    19    64    10    29    96
row3    63    50    25    68    49
row4    17    76    13    96    69
row5    38    82    58    71    51
row6    85    84    46    68    33


In [6]:
df.index=[10,20,30,40,50,60]
print(df)

    col1  col2  col3  col4  col5
10    15    88    89    25    56
20    19    64    10    29    96
30    63    50    25    68    49
40    17    76    13    96    69
50    38    82    58    71    51
60    85    84    46    68    33


In [8]:
#create dataframe from dictionary of series...
dict={
    'name':pd.Series(["Maida","Shumaila","Amna","Soha"]),
    'Age':pd.Series([26,24,27,26]),
    'Address':pd.Series(["Sialkot","Vehari","Lahore","Other"])
}
df1=pd.DataFrame(dict)
print(df1)

       name  Age  Address
0     Maida   26  Sialkot
1  Shumaila   24   Vehari
2      Amna   27   Lahore
3      Soha   26    Other


In [12]:
#create dataframe from dictionary of series with specified row indices...
dict1={
    'name':pd.Series(data=["Maida","Shumaila","Amna","Soha"], index=["m01","m02","m03","m04"]),
    'Age':pd.Series(data=[26,24,27,26], index=["m01","m02","m03","m04"]),
    'Address':pd.Series(data=["Sialkot","Vehari","Lahore","Other"], index=["m01","m02","m03","m04"])
}
df2=pd.DataFrame(dict1)
print(df2)

         name  Age  Address
m01     Maida   26  Sialkot
m02  Shumaila   24   Vehari
m03      Amna   27   Lahore
m04      Soha   26    Other


In [15]:
#create dataframe from dictionary of series with mismatch row indices...
dict2={
    'name':pd.Series(data=["Maida","Shumaila","Amna","Soha"], index=["m01","m02","m03","m04"]),
    'Age':pd.Series(data=[26,24,27,26], index=["m05","m02","m06","m04"]),
    'Address':pd.Series(data=["Sialkot","Vehari","Lahore","Other"], index=["m01","m03","m07","m05"]) #no duplicate indices
}
df3=pd.DataFrame(dict2)
print(df3)

         name   Age  Address
m01     Maida   NaN  Sialkot
m02  Shumaila  24.0      NaN
m03      Amna   NaN   Vehari
m04      Soha  26.0      NaN
m05       NaN  26.0    Other
m06       NaN  27.0      NaN
m07       NaN   NaN   Lahore


In [16]:
#Attributes of dataframe...
df3.shape

(7, 3)

In [17]:
df3.values

array([['Maida', nan, 'Sialkot'],
       ['Shumaila', 24.0, nan],
       ['Amna', nan, 'Vehari'],
       ['Soha', 26.0, nan],
       [nan, 26.0, 'Other'],
       [nan, 27.0, nan],
       [nan, nan, 'Lahore']], dtype=object)

In [18]:
df3.index

Index(['m01', 'm02', 'm03', 'm04', 'm05', 'm06', 'm07'], dtype='object')

In [19]:
df3.columns

Index(['name', 'Age', 'Address'], dtype='object')

In [20]:
df3.size #no of elements

21

In [21]:
df3.ndim

2

In [22]:
df3.dtypes

name        object
Age        float64
Address     object
dtype: object

In [23]:
df3.count() #no of elements in each col excluding NaN values...

name       4
Age        4
Address    4
dtype: int64

In [24]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, m01 to m07
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   name     4 non-null      object 
 1   Age      4 non-null      float64
 2   Address  4 non-null      object 
dtypes: float64(1), object(2)
memory usage: 224.0+ bytes
